### ISSUE TITLE
Request of video

### ISSUE THREAD

**Issue by FXLYZ** [mobarakol/PitVQA#1]
Hi, it is a nice work!

After I submit the application of challenge, I have not get the permission of data.
Could you help me to get the video of PitVQA?

Thanks!

**Comment by mobarakol** [comment]
Hey! Thank you for your kind words about our work!

The preprocessed PitVQA dataset can be found here: https://doi.org/10.5522/04/27004666

You can directly use it to validate our trained weights. If you encounter any issues, feel free to reach out again, and I'll be happy to assist!
